#Written by CorePropertiesLocator
#Tue Mar 24 08:15:47 UTC 2026
collection=climate_change_core
collection.configName=climate_change_core
coreNodeName=core_node2
name=climate_change_core_shard1_replica_n1
replicaType=NRT
shard=shard1
