#Written by CorePropertiesLocator
#Fri Apr 10 16:28:37 UTC 2026
collection=._designer_test
collection.configName=._designer_test
coreNodeName=core_node2
name=._designer_test_shard1_replica_n1
replicaType=NRT
shard=shard1
