#Written by CorePropertiesLocator
#Fri Apr 10 16:31:36 UTC 2026
collection=._designer_climate_change_core
collection.configName=._designer_climate_change_core
coreNodeName=core_node2
name=._designer_climate_change_core_shard1_replica_n1
replicaType=NRT
shard=shard1
